package Gradle

import java.io.File

/**
 * Scaffold a brand-new standalone gradle project from scratch.
 *
 * Writes a `settings.gradle.kts`, a `build.gradle.kts` (Kotlin JVM by default),
 * a `gradle.properties`, a `.gitignore`, and a minimal gradle wrapper invocation
 * script. The wrapper jar is not bundled with the JAR (gradle's wrapper jar is
 * generated by the gradle distribution itself); v1 of the scaffolder writes a
 * `gradle/wrapper/gradle-wrapper.properties` file and a thin shell script that
 * points the user at `gradle wrapper` to finish bootstrap.
 *
 * @since added in v2.
 */
object ProjectScaffolder
{
    /**
     * @param rootDir The directory to scaffold into. Will be created if it does
     *               not exist.
     * @param projectName The project name (used in `rootProject.name` and as the
     *                    default subproject name).
     * @param group The Maven group, e.g. "com.example".
     * @param version The project version, e.g. "0.1.0".
     * @param language The starter language for the root `build.gradle.kts`.
     * @return The [File] pointing at the new project's root.
     */
    fun scaffold(
        rootDir : File,
        projectName : String,
        group : String,
        version : String,
        language : SubprojectScaffolder.Language = SubprojectScaffolder.Language.KOTLIN_JVM,
    ) : File
    {
        if(!rootDir.exists())
        {
            rootDir.mkdirs()
        }

        val settings = File(rootDir, "settings.gradle.kts")
        settings.writeText(
            """
            rootProject.name = "$projectName"

            """.trimIndent()
        )

        val build = File(rootDir, "build.gradle.kts")
        val buildContent = when(language)
        {
            SubprojectScaffolder.Language.KOTLIN_JVM -> kotlinJvmBuild(projectName, group, version)
            SubprojectScaffolder.Language.KOTLIN_MULTIPLATFORM -> kotlinMultiplatformBuild(projectName, group, version)
            SubprojectScaffolder.Language.JAVA -> javaBuild(projectName, group, version)
        }
        build.writeText(buildContent)

        val gradleProps = File(rootDir, "gradle.properties")
        gradleProps.writeText(
            """
            kotlin.code.style=official
            org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
            """.trimIndent() + "\n"
        )

        val gitignore = File(rootDir, ".gitignore")
        gitignore.writeText(
            """
            .gradle/
            build/
            !gradle/wrapper/gradle-wrapper.jar
            *.iml
            .idea/
            """.trimIndent() + "\n"
        )

        //We do not bundle the gradle wrapper jar (it is a binary artifact owned by
        //gradle's distribution). We write a thin `gradle/wrapper/gradle-wrapper.properties`
        //that points at a known-good gradle 8.x version; the user runs `gradle wrapper`
        //once to finish bootstrap.
        val wrapperDir = File(rootDir, "gradle/wrapper")
        wrapperDir.mkdirs()
        val wrapperProps = File(wrapperDir, "gradle-wrapper.properties")
        wrapperProps.writeText(
            """
            distributionBase=GRADLE_USER_HOME
            distributionPath=wrapper/dists
            distributionUrl=https\://services.gradle.org/distributions/gradle-8.14.4-bin.zip
            zipStoreBase=GRADLE_USER_HOME
            zipStorePath=wrapper/dists
            """.trimIndent() + "\n"
        )

        //A `gradlew` script is intentionally not generated because we don't want to
        //ship a binary; the scaffolder prints the bootstrap instructions instead and
        //returns. The user runs `gradle wrapper` (using a system gradle install) to
        //generate gradlew/gradlew.bat on first use.
        return rootDir
    }


    private fun kotlinJvmBuild(name : String, group : String, version : String) : String
    {
        return """
            plugins {
                kotlin("jvm") version "2.2.0"
            }

            group = "$group"
            version = "$version"

            repositories {
                mavenCentral()
            }

            dependencies {
                testImplementation(kotlin("test"))
            }

            tasks.test {
                useJUnitPlatform()
            }

            kotlin {
                jvmToolchain(21)
            }
        """.trimIndent() + "\n"
    }


    private fun kotlinMultiplatformBuild(name : String, group : String, version : String) : String
    {
        return """
            plugins {
                kotlin("multiplatform") version "2.2.0"
            }

            group = "$group"
            version = "$version"

            kotlin {
                jvm()
            }

            sourceSets {
                commonMain.dependencies {
                    //shared deps go here
                }
            }
        """.trimIndent() + "\n"
    }


    private fun javaBuild(name : String, group : String, version : String) : String
    {
        return """
            plugins {
                java
            }

            group = "$group"
            version = "$version"

            repositories {
                mavenCentral()
            }

            java {
                toolchain {
                    languageVersion.set(JavaLanguageVersion.of(21))
                }
            }
        """.trimIndent() + "\n"
    }
}
